src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MovieRepository::class)
 */
class Movie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $release_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $summary;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="string", length=2100, nullable=true)
     */

    private $poster;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $rating;

    /**
     * @ORM\OneToMany(targetEntity=Season::class, mappedBy="movie", orphanRemoval=true)
     */
    private $seasons;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="movies")
     */
    private $genres;

    /**
     * @ORM\OneToMany(targetEntity=Casting::class, mappedBy="movie")
     */
    private $castings;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="movie", orphanRemoval=true)
     */
    private $reviews;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->castings = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(?float $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * @return Collection<int, Season>
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setMovie($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->removeElement($season)) {
            // set the owning side to null (unless already changed)
            if ($season->getMovie() === $this) {
                $season->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection<int, Casting>
     */
    public function getCastings(): Collection
    {
        return $this->castings;
    }

    public function addCasting(Casting $casting): self
    {
        if (!$this->castings->contains($casting)) {
            $this->castings[] = $casting;
            $casting->setMovie($this);
        }

        return $this;
    }

    public function removeCasting(Casting $casting): self
    {
        if ($this->castings->removeElement($casting)) {
            // set the owning side to null (unless already changed)
            if ($casting->getMovie() === $this) {
                $casting->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setMovie($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getMovie() === $this) {
                $review->setMovie(null);
            }
        }

        return $this;
    }
}

src/Form/MovieType.php
<?php

namespace App\Form;

use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [

                'label' => 'title',

                'required' => false,

            ])
            ->add('release_date', DateType::class, [

                'label' => 'crée le',
                'required' => false,

            ])

            ->add('duration', IntegerType::class, [

                'label' => 'durée',
                'required' => false,

            ])
            ->add('type', textType::class, [

                'label' => 'type',

            ])
            ->add('summary', TextareaType::class, [

                'label' => 'résumé',
                'required' => false,

            ])
            ->add('synopsis', TextareaType::class, [

                'label' => 'synopsis',
                'required' => false,

            ])

            ->add('poster', FileType::class, [

                'label' => 'photo',
                'mapped' => false,
                'required' => false,

            ])
            ->add('rating', IntegerType::class, [

                'label' => 'note',
                'mapped' => false,
                'required' => false,

            ])

            ->add('save', SubmitType::class, [
                'attr' => [
                    'class' => 'save',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Movie::class,
        ]);
    }
}

src/Controller/back/MovieController.php
<?php

namespace App\Controller\back;

use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MovieController extends AbstractController
{
    /**
     * @Route("/browse", name="app_browse")
     */
    public function browse(MovieRepository $movieRepository): Response
    {
        $movies = $movieRepository->findAll();
        return $this->render('back/movie/browse.html.twig', [
            'movies' => $movies,
        ]);
    }
    /**
     * @Route("/add", name="app_back_movie_add", methods={"GET", "POST"})
     */

    public function add(Request $request, MovieRepository $movieRepository): Response
    {
        $movie = new Movie();
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $movieRepository->add($movie, true);

            return $this->redirectToRoute('app_browse', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/movie/add.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/show/{id}", name="app_back_movie_show", methods={"GET"})
     */
    public function show(Movie $movie): Response
    {
        return $this->render('back/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_back_movie_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Movie $movie, MovieRepository $movieRepository): Response
    {
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $movieRepository->add($movie, true);

            return $this->redirectToRoute('app_browse', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/movie/edit.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/remove/{id}", name="app_back_Movie_delete", methods={"GET"})
     */
    public function delete($id, MovieRepository $movieRepository): Response
    {
        $movie = $movieRepository->find($id);
        $movieRepository->remove($movie, $flush = true);
        return $this->redirectToRoute('app_browse');
    }
}

src/Controller/front/DemoSessionController.php
<?php

namespace App\Controller\front;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DemoSessionController extends AbstractController
{
    /**
     * @Route("/demo/session", name="app_demo_session")
     */
    public function index(Request $request): Response
    {

        $session = $request->getSession();
        dump($session);
        $username = $session->get('username');
        return $this->render('demo_session/index.html.twig', [
            'username' => $username,
        ]);
    }

    /**
     * Undocumented function
     *
     * @param Request $request
     * @Route("/demo/session/add")
     */

    public function add(Request $request)
    {
        $session = $request->getSession();
        $session->set('username', 'jeremy-le-goff');
        return $this->redirectToRoute('app_demo_session');
    }
}

src/Controller/front/MainController.php
<?php

namespace App\Controller\front;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Model\Movie;

/**
 * On étends AbstractController => c'est comme ca dans tous les controller dans symfony, car AbstractController nous offre plein de méthodes dont on va avoir besoin dans nos controller
 */
class MainController extends AbstractController
{
    /**
     * Page d'accueil
     * 
     * @Route("/", name="home")
     */
    public function home()
    {
        $movies = Movie::getMovies();
        // retourne la vue twig home.html.twig
        return $this->render('main/home.html.twig', [
            //je passe $movies à ma view
            'movies' => $movies
        ]);
    }
}

src/Controller/front/MovieController.php
<?php

namespace App\Controller\front;

use App\Model\Movie;
use App\Repository\CastingRepository;
use App\Repository\MovieRepository;
use App\Repository\ReviewRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 *@Route("/movie")
 */

class MovieController extends AbstractController
{
    /**
     * @Route("/", name="app_movie_list")
     */
    public function index(): Response
    {
        return $this->render('front/movie/list.html.twig', [
            'controller_name' => 'MovieController',
        ]);
    }

    /**
     * Page ma liste
     * 
     * @Route("/favorite", name="app_movie_favorites")
     */

    public function favorite()
    {
        return $this->render('front/movie/favorite.html.twig');
    }

    /**
     * Page de détail d'un film
     *
     * @Route("/show/{id}", name="app_movie_show", methods={"GET"})
     */

    public function show($id, MovieRepository $movieRepository, CastingRepository $castingRepository)
    {

        $movie = $movieRepository->find($id);
        $castingsByCredit = $castingRepository->findByCastingToMovie($movie);
        dump($castingsByCredit);



        if ($movie === null) {
            throw $this->createNotFoundException('Film ou série non trouvé');
        }
        return $this->render('front/movie/show.html.twig', [
            'movie' => $movie,
            'castingsByCredit' => $castingsByCredit
        ]);
    }
}

src/Controller/front/ReviewController.php
<?php

namespace App\Controller\front;

use App\Entity\Movie;
use App\Entity\Review;
use App\Form\ReviewType;
use App\Repository\MovieRepository;
use App\Repository\ReviewRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;




class ReviewController extends AbstractController
{
    /**
     * @Route("/review/{id}", name="app_review")
     */
    public function add(Movie $movie, Request $request, ReviewRepository $reviewRepository): Response
    {
        // dd($movie);
        // On créer une instance de review, c'est cette instance qu'on va manipuler dans le formulaire
        $review = new Review();

        // J'associe $review a mon formulaire
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // dd($review);
            // On associe le film $movie a notre critique $review
            $review->setMovie($movie);
            // On ajoute $review en bdd
            $reviewRepository->add($review, true);
            return $this->redirectToRoute("app_movie_show", ['id' => $movie->getId()]);
        }

        // On utilise renderForm pour retourner une vue avec un formulaire
        // Si on utilisait render(), le form ne s'afficherait pas
        return $this->renderForm('front/review/add.html.twig', [
            'movie' => $movie,
            'form' => $form
        ]);
    }
}

templates/front/movie/favorite.html.twig
{# Ici j'inclus le layout modele base.html.twig #}
{% extends "front/base.html.twig" %}
 {% block body %}

    <div class="container-xl bg-light p-5 border-top">

        <div class="row mb-2">

            <h2 class="text-muted fw-bold mb-4">Ma liste</h2>

            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>A bug's life</strong> a été ajouté à votre liste de favoris.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            <div class="col-6">

                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm bg-white position-relative">
                    <div class="col-4 movie__poster" style="background-image: url(https://m.media-amazon.com/images/M/MV5BNThmZGY4NzgtMTM4OC00NzNkLWEwNmEtMjdhMGY5YTc1NDE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg);">
                        <img src="{{ asset('images/poster-placeholder.png') }}" class="img-fluid">
                        <!-- img src="https://m.media-amazon.com/images/M/MV5BNThmZGY4NzgtMTM4OC00NzNkLWEwNmEtMjdhMGY5YTc1NDE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" class="img-fluid" -->
                    </div>
                    <div class="col-8 p-4 d-flex flex-column position-static">
                        <a href="" class="movie__favorite fs-1 my-2 mx-3 link-danger"><i class="bi bi-bookmark-x-fill"></i></a>
                        <strong class="d-inline-block mb-2 text-primary">Film</strong>
                        <h3 class="mb-1">A Bug's Life</h3>
                        <div class="mb-1 text-muted">93 min</div>
                        <a href="./show.html" class="fs-1 mt-3 text-danger align-self-start">
                            <i class="bi bi-arrow-right-square"></i>
                        </a>
                    </div>
                </div>
            
            </div>

            <div class="col-6">

                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm bg-white position-relative">
                    <div class="col-4 movie__poster" style="background-image: url(https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg);">
                        <!-- img src="https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg"
                            class="img-fluid" -->
                        <img src="images/poster-placeholder.png" alt="">
                    </div>
                    <div class="col-8 p-4 d-flex flex-column position-static">
                        <a href="" class="movie__favorite fs-1 my-2 mx-3 link-danger"><i class="bi bi-bookmark-x-fill"></i></a>
                        <strong class="d-inline-block mb-2 text-success">Série</strong>
                        <h4 class="mb-1">Game of Thrones</h4>
                        <div class="mb-1 text-muted">52 min</div>
                        <a href="" class="fs-1 mt-3 text-danger align-self-start">
                            <i class="bi bi-arrow-right-square"></i>
                        </a>
                        
                    </div>
                </div>
            </div>

            <div class="col-6">

                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm bg-white position-relative">
                    <div class="col-4 movie__poster" style="background-image: url(https://m.media-amazon.com/images/M/MV5BN2ZmYjg1YmItNWQ4OC00YWM0LWE0ZDktYThjOTZiZjhhN2Q2XkEyXkFqcGdeQXVyNjgxNTQ3Mjk@._V1_SX300.jpg);">
                        <!-- img src="https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg"
                            class="img-fluid" -->
                        <img src="images/poster-placeholder.png" alt="">
                    </div>
                    <div class="col-8 p-4 d-flex flex-column position-static">
                        <a href="" class="movie__favorite fs-1 my-2 mx-3 link-danger"><i class="bi bi-bookmark-x-fill"></i></a>
                        <strong class="d-inline-block mb-2 text-success">Série</strong>
                        <h4 class="mb-1">Stranger Things</h4>
                        <div class="mb-1 text-muted">50 min</div>
                        <a href="" class="fs-1 mt-3 text-danger align-self-start">
                            <i class="bi bi-arrow-right-square"></i>
                        </a>
                        
                    </div>
                </div>
            </div>

        </div>

        <div class="col">
            <a href="" class="btn btn-danger btn-sm" onclick="return confirm('Vider votre liste de favoris ?');">Vider la liste</a>
        </div>

     </div>
{% endblock %}

templates/front/movie/list.html.twig
 {# Ici j'inclus le layout modele base.html.twig #}
{% extends "front/base.html.twig" %}

 {% block body %}
    <div class="container-xl bg-light p-5 border-top">

        <div class="row mb-2">

            <div class="col-12 col-lg-3">
                <h2 class="text-center text-muted fw-bold mb-4">Les genres</h2>
                <ul class="d-flex flex-column flex-wrap list-unstyled justify-content-center">
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Action</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Animation</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Aventure</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Comédie</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Dessin animé</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Documentaire</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Drame</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Espionnage</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Famille</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Fantastique</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Historique</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Policier</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Romance</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Science-fiction</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Thriller</li>
                    <li class="btn btn-sm btn-outline-danger mx-1 mb-2">Western</li>
                </ul>
            </div>

            <div class="col-12 col-lg-9">

                <h2 class="text-muted fw-bold mb-4">Les films et séries/Résultats de recherche</h2>

                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm bg-white position-relative">
                    <div class="col-4 movie__poster" style="background-image: url(https://m.media-amazon.com/images/M/MV5BNThmZGY4NzgtMTM4OC00NzNkLWEwNmEtMjdhMGY5YTc1NDE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg);">
                        <img src="{{ asset('images/poster-placeholder.png') }}" class="img-fluid">
                        <!-- img src="https://m.media-amazon.com/images/M/MV5BNThmZGY4NzgtMTM4OC00NzNkLWEwNmEtMjdhMGY5YTc1NDE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" class="img-fluid" -->
                    </div>
                    <div class="col-8 p-4 d-flex flex-column position-static">
                        <a href="" class="movie__favorite fs-1 my-2 mx-3 link-danger"><i class="bi bi-bookmark-plus"></i></a>
                        <strong class="d-inline-block mb-2 text-primary">Film</strong>
                        <h3 class="mb-1">A Bug's Life</h3>
                        <div class="mb-1 text-muted">93 min</div>
                        <p><small>Tilt, fourmi quelque peu tête en l'air, détruit par
                                inadvertance la
                                récolte de la saison.</small>
                        </p>
                        <div class="d-flex" style="color: orange;">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-half"></i>
                            <span class="ps-1">4.8</span>
                        </div>
                        <a href="./show.html" class="fs-1 mt-3 text-danger align-self-start">
                            <i class="bi bi-arrow-right-square"></i>
                        </a>
                    </div>
                </div>

                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm bg-white position-relative">
                    <div class="col-4 movie__poster" style="background-image: url(https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg);">
                        <!-- img src="https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg"
                            class="img-fluid" -->
                        <img src="images/poster-placeholder.png" alt="">
                    </div>
                    <div class="col-8 p-4 d-flex flex-column position-static">
                        <a href="" class="movie__favorite fs-1 my-2 mx-3 link-danger"><i class="bi bi-bookmark-x-fill"></i></a>
                        <strong class="d-inline-block mb-2 text-success">Série</strong>
                        <h4 class="mb-1">Game of Thrones</h4>
                        <div class="mb-1 text-muted">50 min</div>
                        <p><small>Nine noble families fight for control over the lands of Westeros,
                                while an
                                ancient enemy returns...</small>
                        </p>
                        <div class="d-flex" style="color: orange;">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-half"></i>
                            <i class="bi bi-star"></i>
                            <span class="ps-1">3.7</span>
                        </div>
                        <a href="" class="fs-1 mt-3 text-danger align-self-start">
                            <i class="bi bi-arrow-right-square"></i>
                        </a>
                        
                    </div>
                </div>
            </div>
        {% endblock %}

templates/front/movie/show.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}O'Flix{% endblock %}

{% block body %}
<div class="container bg-lighttt pt-5">

        <div class="row mb-2">

            <div class="col">

                <div
                    class="row g-0 borderrr rrrounded overflow-hidden flex-md-row align-items-start mb-4 shadow-smmm position-relative">
                    <div class="col-4 movie__poster img-thumbnail"
                        style="background-image: url({{ movie.poster }});">
                        <img src="{{ asset('images/poster-placeholder.png') }}" class="img-fluid">
                        <!-- img src="https://m.media-amazon.com/images/M/MV5BNThmZGY4NzgtMTM4OC00NzNkLWEwNmEtMjdhMGY5YTc1NDE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" class="img-fluid" -->
                    </div>
                    <div class="col-8 p-4 d-flex flex-column position-static bg-light">
                        <a href="" class="movie__favorite fs-1 my-2 mx-3 link-danger"><i class="bi bi-bookmark-plus"></i></a>
                        <strong class="d-inline-block mb-2 text-primary"> {{movie.type }}</strong>
                        <h3 class="mb-1">{{ movie.title }}</h3>
                        <div class="mb-1 text-muted">{{ movie.duration }} min</div>
                        <p>
                            {% for genre in movie.genres %}
                                <span class="badge bg-warning text-dark">{{ genre.name }}</span>
                            {% endfor %}
                        </p>
                        <p>
                            {{ movie.synopsis }}
                        </p>
                        <div class="d-flex mb-4" style="color: orange;">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-half"></i>
                            <span class="ps-1">{{ movie.rating }}</span>
                        </div>
                        {% if movie.type == 'Série' %}
                        <h2>3 Saisons</h2>
                        <ul class="list-unstyled">
                            <li><span class="badge bg-danger fs-6 mb-2">Saison 1</span><small class="ms-1">(10 épisodes)</small></li>
                            <li><span class="badge bg-danger fs-6 mb-2">Saison 2</span><small class="ms-1">(11 épisodes)</small></li>
                            <li><span class="badge bg-danger fs-6 mb-2">Saison 3</span><small class="ms-1">(12 épisodes)</small></li>
                        </ul>
                        {% endif %}

                        <dl class="row">
                            <dt class="col-sm-12">Avec</dt>
                            <dd class="col-sm-12">
                            {% for casting in castingsByCredit %}
                                {{ casting.person.firstname }} {{ casting.person.lastname }} ({{ casting.role }}) <br>
                            {% endfor %}
                            </dd>
                            <dt class="col-sm-12">Pays</dt>
                            <dd class="col-sm-12">USA</dd>
                            <dt class="col-sm-12">Année</dt>
                            <dd class="col-sm-12">{{ movie.releaseDate|date("Y") }}</dd>
                        </dl>
                        <h2>ajouter une critique </h2>
                        <a class="btn btn-sm btn-warning" href="{{ path('app_review', {id:movie.id}) }}">Ajouter une critique</a>
                         {% for review in movie.reviews %}
                            <p>
                                {{ review.content }}
                                <small>{{ review.username }}</small>
                            </p>
                            {% endfor %}
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}